# Generated by Django 4.1.2 on 2022-10-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome Produto')),
                ('description', models.TextField(verbose_name='Descrição Produto')),
                ('picture', models.ImageField(upload_to='media/product/pictures/', verbose_name='Foto produto')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor Produto')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.seller', verbose_name='Vendedore')),
            ],
        ),
    ]
