# Generated by Django 4.1.2 on 2022-10-26 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('client', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppingart_Client', to='client.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Produto')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='qty',
        ),
        migrations.AddField(
            model_name='purchases',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor Total'),
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor Total')),
                ('itens_shoppingcart', models.ManyToManyField(to='purchases.itensshoppingcart')),
            ],
        ),
    ]
