# Generated by Django 4.1.2 on 2022-10-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50, verbose_name='Rua/Av.')),
                ('city', models.CharField(max_length=50, verbose_name='Cidade')),
                ('number', models.CharField(max_length=6, verbose_name='Numero')),
                ('state', models.CharField(max_length=2, verbose_name='UF')),
                ('district', models.CharField(max_length=50, verbose_name='Bairro')),
                ('reference', models.CharField(max_length=100, verbose_name='Ponto Referencia')),
            ],
        ),
    ]
